#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# Hunger Disabler Configuration File:
#   Default Config:
#      hunger-disabler: "on"

# The below config turns on or off hunger (OPTIONS: on or off)
hunger-disabler: "on"